name: Frontend workflow

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/*.yml

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js (to build the Angular app)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies and build the Angular app
      - name: Install dependencies and build Angular app
        run: |
          npm install
          npm run build --prod

